name: Django Server Test

on:
  push:
    branches:
      - "*" # Run on all branch pushes
  pull_request:
    branches:
      - main

permissions:
  id-token: write # OIDC requirement
  contents: read

jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add debugging step here, before AWS credential configuration
      - name: Debug OIDC claims
        run: |
          GITHUB_CONTEXT=$(echo $GITHUB_CONTEXT | jq -c .)
          echo "GitHub context: $GITHUB_CONTEXT"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423382885:role/echo
          role-session-name: github-actions-federation
          aws-region: us-west-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Django Server Startup
        run: |
          # Start Django server in background
          python manage.py runserver 0.0.0.0:8000 &
          SERVER_PID=$!

          # Wait for server to initialize
          sleep 5

          # Check if server is running
          if ps -p $SERVER_PID > /dev/null; then
            echo "✅ Django server started successfully"
            # Optional: make a request to check if it responds
            curl -s http://localhost:8000/ || echo "Warning: Server running but may not be responding to requests"
            kill $SERVER_PID
            exit 0
          else
            echo "❌ Django server failed to start"
            exit 1
          fi
