name: Django Server Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_server:
    permissions: 
      id-token: write  # OIDC requirement
      contents: read
      
    runs-on: ubuntu-latest
    environment: aws-mysql
    steps:

      - uses: actions/checkout@v3
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::637423382885:role/Echo
          aws-region: us-west-1
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test Django Server Startup
        run: |
          # Start Django server in background
          python manage.py runserver 0.0.0.0:8000 &
          SERVER_PID=$!
          
          # Wait for server to initialize
          sleep 5
          
          # Check if server is running
          if ps -p $SERVER_PID > /dev/null; then
            echo "✅ Django server started successfully"
            # Optional: make a request to check if it responds
            curl -s http://localhost:8000/ || echo "Warning: Server running but may not be responding to requests"
            kill $SERVER_PID
            exit 0
          else
            echo "❌ Django server failed to start"
            exit 1
          fi
